version: '3.4'

services:
  http-db:
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB:       http
      POSTGRES_USER:     http
      POSTGRES_PASSWORD: http
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "http"]
      interval: 10s
      timeout: 5s
      retries: 5
